### ISSUE TITLE
How to deal with protocols and empty strings

### ISSUE THREAD

**Issue by ZauberNerd** [untool/pathifist#25]
I found a few cases where I was questioning what `pathifist` does:

- `join('http://localhost:8080', 'foo')` returns `http:/localhost:8080/foo`
- `resolve('http://localhost:8080', '/foo', 'bar')` returns `http:/localhost:8080/bar`
- `ensureLeadingSlashes('')` returns `/`
- `ensureTrailingSlashes('')` returns `/`
- `dedupeSlashes('http://localhost:8080//foo//bar')` returns `http:/localhost:8080/foo/bar`

Are these cases that we want to handle differently or is this behaviour expected?

**Comment by dmbch** [comment]
All of the above are expected behavior - some of `pathifist`’s methods would not even make sense if applied to URLs, e.g. `trimLeadingSlashes`.

That being said, I would not really mind adding URL/protocol enabled versions to those methods we consider relevant.

**Comment by dmbch** [comment]
@ZauberNerd do you want to follow up on this or can we close this issue in your opinion?

**Comment by dmbch** [comment]
I assume we can consider this answered/resolved for now. Feel free to re-open if I got it wrong!
